openapi: 3.0.3
info:
  title: ai operate - OpenAPI 3.0
  description: |-
    This is ai operate OpenAPI.
  version: 1.0.0
components:
  schemas:
    FileDto:
      type: object
      properties:
        id:
          type: integer
          description: 文件ID
        fullFileName:
          type: string
          description: 文件全名
        url:
          type: string
          description: 文件URL
    RagInfoDto:
      type: object
      properties:
        textChunkId:
          type: string
          description: 文本块ID
        textChunk:
          type: string
          description: 文本块
        srcFile:
          $ref: '#/components/schemas/FileDto'
    LoginRequestDto:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
        validateCode:
          type: string
          description: 验证码
        hash:
          type: string
          description: 验证码Hash
    SlideCaptchaResp:
      type: object
      description: 滑动验证码
      properties:
        hash:
          type: string
          description: 验证码签名
        puzzleUrl:
          type: string
          description: 凹槽图片url
        width:
          type: integer
          format: int32
          description: 凹槽图片宽度
        height:
          type: integer
          format: int32
          description: 凹槽图片高度
        sliderUrl:
          type: string
          description: 滑块图片url
        sliderSize:
          type: integer
          format: int32
          description: 滑块图片宽度
        sliderY:
          type: number
          format: float
          description: 滑块图片高度
    EmbeddingsRequestDto:
      type: object
      properties:
        input:
          type: array
          items:
            type: string
    EmbeddingsResponseDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/EmbeddingsDtoItem'
    EmbeddingsDtoItem:
      type: object
      properties:
        hash:
          type: string
        embeddingModel:
          type: string
        embeddingProvider:
          type: string
        text:
          type: string
        embeddings:
          type: array
          items:
            type: number
            format: float
    KnowledgeRetrieveItemDto:
      type: object
      properties:
        hash:
          description: 嵌入text的哈希值（SHA-1），同时也作为唯一标识符
          type: string
        score:
          description: 匹配度[-1,1]
          type: number
          format: float
        hybridScore:
          description: 混合检索得分
          type: number
          format: float
        denseScore:
          description: 稠密向量检索得分
          type: number
          format: float
        sparseScore:
          description: 稀疏向量检索得分
          type: number
          format: float
        metricType:
          type: string
          enum: [ "L2", "IP", "COSINE", "JACCARD", "HAMMING" ]
        denseMetricType:
          description: 稠密向量检索指标
          type: string
          enum: [ "L2", "IP", "COSINE", "JACCARD", "HAMMING" ]
        sparseMetricType:
          description: 稀疏向量检索指标
          type: string
          enum: [ "BM25" ]
        embeddingModel:
          type: string
        embeddingProvider:
          type: string
        dimension:
          description: 嵌入向量的维度
          type: integer
        outline:
          description: 嵌入文本值
          type: string
        textChunk:
          description: 文本块
          type: string
        textChunkId:
          description: 文本块ID
          type: string
        isFiltered:
          type: boolean
          default: false
          description: 是否被表达式过滤
    KnowledgeGetListDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/KnowledgeDto'
    KnowledgeDto:
      type: object
      properties:
        textChunkId:
          type: string
          description: 知识ID（文本块的SHA-1）
        outline:
          type: array
          description: 知识概要（用于嵌入后检索的文本）
          items:
            type: string
        textChunk:
          type: string
          description: 文本块
        embeddingModel:
          type: string
          description: 嵌入模型名称
        embeddingProvider:
          type: string
          description: 嵌入模型提供商名称
        dimension:
          description: 嵌入向量的维度
          type: integer
        description:
          type: string
          description: 描述
        fileName:
          type: string
          description: 文件名
        fileId:
          type: integer
          description: 文件ID
        createTime:
          type: integer
          description: 创建时间
          format: int64
        updateTime:
          type: integer
          description: 更新时间
          format: int64
        createUsername:
          type: string
          description: 创建者
    KnowledgeAddDto:
      type: object
      properties:
        id:
          type: string
          description: 知识ID（textChunk的SHA-1）
        outline:
          type: array
          description: 知识概要（用于检索）
          items:
            type: string
        textChunk:
          type: string
          description: 文本块
        description:
          type: string
          description: 描述
        fileId:
          type: integer
          description: 文件ID
        classify:
          type: string
          description: 分类（/分隔）
          example: 数通/配置
        fileLocation:
          type: string
          description: 文件中的位置
    KnowledgeRetrieveResponseDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/KnowledgeRetrieveItemDto'
    QaTemplateItem:
      type: object
      properties:
        question:
          type: string
          description: 问题
    QaTemplateList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/QaTemplateItem'
    ContextIdDto:
      type: object
      properties:
        contextId:
          type: string
    MessageDto:
      type: object
      description: 聊天消息
      properties:
        index:
          type: integer
          description: 消息序号
        role:
          type: string
          enum: [ "system", "user", "assistant", "tool" ]
          description: 角色
        content:
          type: string
          description: 消息内容
        feedback:
          type: integer
          description: 反馈
          enum: [ 0, 1, 2 ]
          x-enum-varnames: [ "NONE", "GOOD", "BAD" ]
        srcFile:
          type: array
          items:
            $ref: '#/components/schemas/FileDto'
    ChatRequestDto:
      type: object
      properties:
        contextId:
          type: string
          description: 会话ID
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MessageDto'
        retrievalKb:
          type: boolean
          description: 是否检索知识库
          default: true
        toolGroupName:
          type: array
          description: 使用的工具组
          default: [ "general" ]
          items:
            type: string
        systemPrompt:
          type: string
          description: 系统提示词
          default: GENERAL_ASSISTANT
          enum: [ GENERAL_ASSISTANT, TOOL_USE ]
    ChatResponseDto:
      type: object
      properties:
        contextId:
          type: string
          description: 聊天上下文ID
        message:
          $ref: '#/components/schemas/MessageDto'
        done:
          type: boolean
          default: false
        error:
          type: boolean
          default: false
        errorCode:
          type: string
        errorMessage:
          type: string
    HistoryContextList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/HistoryContextItem'
    HistoryContextItem:
      type: object
      description: 聊天历史
      properties:
        contextId:
          type: string
          description: 聊天上下文ID
        title:
          type: string
          description: 标题
        lastUpdateTime:
          type: integer
          format: int64
          description: 最后访问时间
    ChatContextDto:
      type: object
      description: 聊天对话上下文
      properties:
        contextId:
          type: string
          description: 聊天上下文ID
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MessageDto'
    MessageFeedbackRequest:
      type: object
      properties:
        contextId:
          type: string
          description: 上下文ID
        index:
          type: integer
          description: 消息序号
        feedback:
          type: integer
          description: 反馈
          enum: [ 0, 1, 2 ]
          x-enum-varnames: [ "NONE", "GOOD", "BAD" ]
    CheckApiResponse:
      type: object
      properties:
        status:
          type: integer
          description: 0 - 正常，1 - 连接异常，2 - 认证异常
          enum: [ 0, 1, 2 ]
          x-enum-varnames: [ "NORMAL", "CONNECT_ERROR", "AUTH_ERROR" ]
        description:
          type: string
          description: 描述
    PropertyDto:
      type: object
      properties:
        propertyName:
          type: string
          description: 属性名称
        propertyValue:
          type: string
          description: 值