server:
  port: 30110
  servlet:
    encoding:
      charset: UTF-8 # 需要强制设置编码，否则SSE会出现乱码
      force: true
spring:
  application:
    name: ai
  web:
    resources:
      static-locations: classpath:/dist/
jrag:
  security:
    captcha:
      expire-seconds: 300
  # 是否为公共模式（免登录，历史回话存在于浏览器）
  public-mode: false
  llm:
    demo: false
    temperature: 0.5
    llm-provider: open-ai
    use-tools: true
    ollama:
#      model-name: qwen3:14b
#      base-url: http://127.0.0.1:11434
#      # 模型驻留时间
#      keep_alive_seconds: 3600
#      context-length: 32768

      model-name: qwen3:14b-q8_0
      base-url: http://172.16.8.107:11434
      # 模型驻留时间
      keep_alive_seconds: 3600
      context-length: 32768
    open-ai:
      model-name: qwen3-14b-mlx
      base-url: http://127.0.0.1:1234
      completions-path: /v1/chat/completions
      key:
#      model-name: 4.0Ultra
#      base-url: https://spark-api-open.xf-yun.com
#      completions-path: /v1/chat/completions
#      key: RSvigWgMWgarwaTMNuBn:jMbCLBVJezEiHSqFCgpR
#      use-tools: true
  embedding:
    # 嵌入向量维度
    dimension: 768
    embedding-provider: open-ai
    ollama:
      model-name: nomic-embed-text:latest
      base-url: http://127.0.0.1:11434
      # 模型驻留时间
      keep_alive_seconds: 3600
    open-ai:
      model-name: text-embedding-nomic-embed-text
      base-url: http://127.0.0.1:1234
      embeddings-path: /v1/embeddings
      key:
  vector-database:
    provider: redis
    milvus:
      cluster-endpoint: http://127.0.0.1:19530
      collection-name: jrag
      token: root:Milvus
    redis:
      host: 127.0.0.1
      port: 6379
      username:
      password:
      key-prefix: jrag
  file:
    upload-path: classpath:/file
    static-path: classpath:/static-file
  rag:
    md-location: