server:
  port: 30110
  servlet:
    encoding:
      charset: UTF-8 # 需要强制设置编码，否则SSE会出现乱码
      force: true
spring:
  application:
    name: ai
  web:
    resources:
      static-locations: classpath:/dist/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB # 文件最大上传大小
      max-request-size: 10GB # 请求最大上传大小
jrag:
  security:
    captcha:
      expire-seconds: 300
  llm:
    demo: false
    temperature: 0.5
    llm-provider: open-ai
    use-rag: true
    use-tools: true
    ollama:
      model-name: qwen3:14b
      base-url: http://127.0.0.1:11434
      # 模型驻留时间
      keep_alive_seconds: 3600
      context-length: 32768
    open-ai:
      model-name: Qwen/Qwen3-235B-A22B
      base-url: https://api-inference.modelscope.cn
      completions-path: /v1/chat/completions
      key:
  embedding:
    # 嵌入向量维度
    dimension: 768
    embedding-provider: ollama
    ollama:
      model-name: nomic-embed-text:latest
      base-url: http://127.0.0.1:11434
      # 模型驻留时间
      keep_alive_seconds: 3600
    open-ai:
      model-name: text-embedding-nomic-embed-text
      base-url: http://127.0.0.1:1234
      embeddings-path: /v1/embeddings
      key:
  vector-database:
    provider: redis
    milvus:
      cluster-endpoint: http://127.0.0.1:19530
      collection-name: jrag
      token: root:Milvus
    redis:
      host: 127.0.0.1
      port: 6379
      username:
      password:
      key-prefix: jrag
  file:
    upload-path: ${user.home}/jrag/upload/file
    static-path: ${user.home}/jrag/upload/static-file
  rag:
    md-location: