server:
  port: 30110
  servlet:
    encoding:
      charset: UTF-8 # 需要强制设置编码，否则SSE会出现乱码
      force: true
spring:
  application:
    name: ai
  web:
    resources:
      static-locations: classpath:/dist/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB # 文件最大上传大小
      max-request-size: 10GB # 请求最大上传大小
jrag:
  security:
    captcha:
      expire-seconds: 300
    # 无用户模式
    no-user: false
  vector-database:
    provider: milvus
    milvus:
      cluster-endpoint: http://127.0.0.1:19530
      collection-name: jrag
      token: root:Milvus
  file:
    upload-path: ${user.home}/jrag/upload/file
    static-path: ${user.home}/jrag/upload/static-file
  rag:
    md-location: